export const ADD_INSTRUMENT = 'ADD_INSTRUMENT';
export const DELETE_INSTRUMENT = 'DELETE_INSTRUMENT';
export const RESET_INSTRUMENTS = 'RESET_INSTRUMENTS';
export const APPLY_FILTER = 'APPLY_FILTER';
export const EDIT_INSTRUMENT = 'EDIT_INSTRUMENT';
export const LOAD_INSTRUMENTS_REQUEST = 'LOAD_INSTRUMENTS_REQUEST';
export const LOAD_INSTRUMENTS_SUCCESS = 'LOAD_INSTRUMENTS_SUCCESS';
