export const ADD_PROPOSAL = 'ADD_PROPOSAL';
export const LOAD_PROPOSALS_REQUEST = 'LOAD_PROPOSALS_REQUEST';
export const LOAD_PROPOSALS_SUCCESS = 'LOAD_PROPOSALS_SUCCESS';
export const LOAD_PROPOSALS_ERROR = 'LOAD_PROPOSALS_ERROR';
