export const ADD_MD_SCHEMA = 'ADD_MD_SCHEMA';
export const DELETE_SCHEMA_KEY = 'DELETE_SCHEMA_KEY';
export const EDIT_SCHEMA_KEY = 'EDIT_SCHEMA_KEY';
export const ADD_SCHEMA_KEY = 'ADD_MD_SCHEMA_KEY';
export const LOAD_MD_SCHEMAS_REQUEST = 'LOAD_MD_SCHEMAS_REQUEST';
export const LOAD_MD_SCHEMAS_SUCCESS = 'LOAD_MD_SCHEMAS_SUCCESS';
export const LOAD_MD_SCHEMAS_ERROR = 'LOAD_MD_SCHEMAS_ERROR';
