export const ADD_INSTRUMENT = 'ADD_INSTRUMENT';
export const LOAD_INSTRUMENTS_REQUEST = 'LOAD_INSTRUMENTS_REQUEST';
export const LOAD_INSTRUMENTS_SUCCESS = 'LOAD_INSTRUMENTS_SUCCESS';
export const LOAD_INSTRUMENTS_ERROR = 'LOAD_INSTRUMENTS_ERROR';
