export const ADD_FIXED_VALUE_ENTRY = 'ADD_FIXED_VALUE_ENTRY';
export const LOAD_FIXED_VALUE_ENTRIES_REQUEST = 'LOAD_FIXED_VALUE_ENTRIES_REQUEST';
export const LOAD_FIXED_VALUE_ENTRIES_SUCCESS = 'LOAD_FIXED_VALUE_ENTRIES_SUCCESS';
export const LOAD_FIXED_VALUE_ENTRIES_ERROR = 'LOAD_FIXED_VALUE_ENTRIES_ERROR';
export const DELETE_FIXED_VALUE_ENTRY = 'DELETE_FIXED_VALUE_ENTRY';
export const EDIT_FIXED_VALUE_ENTRY = 'EDIT_FIXED_VALUE_ENTRY';
